version: '3.8'
services:

  gptclone:
    image: si3mshady/rag-fe
    depends_on:
      - pgvector
    container_name: gptclone
    environment: 
      - REACT_APP_API_URL=http://localhost:8080/
      - REACT_APP_REALM=RAG
      - REACT_APP_CLIENT_ID=rag-client
      - REACT_APP_SERVER=localhost
    ports: 
      - "3000:3000"

  dbconnect:
    image: si3mshady/rag-server-be
    depends_on:
      - pgvector
    container_name: rag-server-be    
    environment:
      - OPENAI_API_KEY=sk-7JhICXTXagXyz
      - DATABASE_NAME=rag
      - DATABASE_PASSWORD=test
      - DB_CONTAINER_NAME=pgvector
      - DB_TABLE_NAME=rag-table
    ports: 
      - '5000:5000'

  pgvector:
    image: pgvector/pgvector:pg16
  
    container_name: pgvector
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
 

volumes:
  pgvector_data:
