version: '3.8'
services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - mynetwork

volumes:
  pgvector_data:
  keycloak_data:

networks:
  mynetwork:
    driver: bridge