apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: customer3
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: v1
kind: Service
metadata:
  name: cust3-deployment
  namespace: customer3
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: cust3-deployment
  type: ClusterIP

