apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: customer3
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: v1
kind: Service
metadata:
  name: cust3-deployment
  namespace: customer3
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: cust3-deployment
  type: ClusterIP

helm install cust2-ingress -n cust3 ingress-nginx/ingress-nginx --set controller."kubernetes.io/ingress.class"=customer3
#  593  helm install my-ingress-nginx -n customer2 ingress-nginx/ingress-nginx --set controller."kubernetes.io/ingress.class"=customer3
# kubectl create ingress customer3-ingress  --rule="/=cust3-deployment:3000" -n customer3 --annotation controller.ingressClassName=customer3