apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: customer2
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: k8s.io/ingress-nginx

---

piVersion: v1
kind: Service
metadata:
  name: cust2-deployment
  namespace: customer2
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: gptclone-deployment
  type: ClusterIP

# kubectl create ingress customer2-ingress  --rule="/=cust2-deployment:3000" -n customer3 --annotation controller.ingressClassName=customer2