apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgvector
  template:
    metadata:
      labels:
        io.kompose.service: pgvector
    spec:
      containers:
        - name: pgvector
          image: si3mshady/database_connect:2
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_NAME
              value: rag
            - name: DATABASE_PASSWORD
              value: letsgetiton
            - name: DB_CONTAINER_NAME
              value: "34.82.177.54"
            - name: DB_TABLE_NAME
              value: rag-table
            - name: OPENAI_API_KEY
              value: sk-

---
apiVersion: v1
kind: Service
metadata:
  name: pgvector-service
spec:
  selector:
    io.kompose.service: pgvector
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # nodePort: 30000   # Define a specific NodePort (e.g., 30000)
  type: LoadBalancer        # Change the Service type to NodePort


  # gptclone-service.default.svc.cluster.local

  # gke-app-factory-default-pool-75cf5dd3-qn5s/10.138.0.12