apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgvector
  template:
    metadata:
      labels:
        io.kompose.service: pgvector
    spec:
      containers:
        - name: pgvector
          image: si3mshady/database_connect:1
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_NAME
              value: rag
            - name: DATABASE_PASSWORD
              value: letsgetiton
            - name: DB_CONTAINER_NAME
              value: "34.145.25.147"
            - name: DB_TABLE_NAME
              value: rag-table
            - name: OPENAI_API_KEY
              value: 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

---

apiVersion: v1
kind: Service
metadata:
  name: pgvector-service
spec:
  selector:
    io.kompose.service: pgvector
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
