apiVersion: apps/v1
kind: Deployment
metadata:
  name: gptclone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gptclone
  template:
    metadata:
      labels:
        io.kompose.service: gptclone
    spec:
      containers:
        - name: gptclone
          image: si3mshady/basic_rag:2
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "pgvector"
            - name: REACT_APP_CLIENT_ID
              value: "rag-client"
            - name: REACT_APP_REALM
              value: "RAG"
            - name: REACT_APP_SERVER
              value: "34.168.177.59" 
            - name: REACT_APP_PORT   # Corrected the environment variable definition
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gptclone-service
spec:
  selector:
    io.kompose.service: gptclone
  ports:
    - protocol: TCP
      port: 80   # Exposed port on the Service should match the external port (e.g., 80 for HTTP)
      targetPort: 3000
  type: LoadBalancer