apiVersion: v1
kind: Namespace
metadata:
  name: customer1   # Namespace named "customer1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust1-deployment

  namespace: customer1   # Applying namespace "customer1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust1-deployment

  template:
    metadata:
      labels:
        app: cust1-deployment

    spec:
      containers:
        - name: gptclone
          image: si3mshady/basic_rag:4
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://34.168.31.169:8080/"
            - name: REACT_APP_CLIENT_ID
              value: "rag-client"
            - name: REACT_APP_REALM
              value: "rag"
            - name: REACT_APP_SERVER
              value: "34.168.124.210" 
            - name: REACT_APP_PORT   # Corrected the environment variable definition
              value: "5000"
